name: Call GitHobbit

on:
  push:
    branches:
      - 'main'

jobs:
  fork-the-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Forking the repo
        run: gh repo fork mehtakaran9/test-app-js --fork-name test-app-fork --clone --remote
        env:
          GITHUB_TOKEN: ${{ secrets.access-token }}
  call-workflow:
    uses: mehtakaran9/githobbit/.github/workflows/actions.yml@main
    with:
      owner: mehtakaran9
      repository: test-app-fork
      branch: main
      target-branch: typescript
      file-mode: false
    secrets:
      token: ${{ secrets.access-token }}
