name: Call GitHobbit

on:
  push:
    branches:
      - 'main'

jobs:
  call-workflow:
    uses: mehtakaran9/githobbit/.github/workflows/actions.yml@main
    with:
      owner: mehtakaran99
      repository: test-app-js
      branch: main
      target-branch: typescript
      file-mode: false
